import type { CandidateModel } from "../shared/types.js";

export const curatedTextModels: CandidateModel[] = [
  {
    id: "google/gemma-2-2b-it",
    kind: "text",
    family: "gemma",
    runtime: ["ollama", "transformers", "llamacpp"],
    tasks: ["text_generation", "writing", "general_chat"],
    localFriendly: true,
    estimatedRamGb: 6,
    speedTier: 5,
    qualityTier: 3,
    source: "seed",
    gated: false,
    formats: ["gguf", "safetensors"],
    parameterClass: "small",
    memoryProfile: {
      minRamGb: 6,
      recommendedRamGb: 10,
    },
    discoveryConfidence: "high",
    notes: ["Very small footprint for 8 GB class machines."],
  },
  {
    id: "meta-llama/Llama-3.2-3B-Instruct",
    kind: "text",
    family: "llama",
    runtime: ["ollama", "transformers", "llamacpp"],
    tasks: ["text_generation", "general_chat", "documents"],
    localFriendly: true,
    estimatedRamGb: 7,
    speedTier: 5,
    qualityTier: 3,
    source: "seed",
    gated: false,
    formats: ["gguf", "safetensors"],
    parameterClass: "small",
    memoryProfile: {
      minRamGb: 7,
      recommendedRamGb: 11,
    },
    discoveryConfidence: "high",
    notes: ["Strong small model for tight RAM budgets."],
  },
  {
    id: "microsoft/Phi-3.5-mini-instruct",
    kind: "text",
    family: "phi",
    runtime: ["ollama", "transformers"],
    tasks: ["text_generation", "writing", "general_chat"],
    localFriendly: true,
    estimatedRamGb: 8,
    speedTier: 5,
    qualityTier: 3,
    source: "seed",
    gated: false,
    formats: ["safetensors", "other"],
    parameterClass: "small",
    memoryProfile: {
      minRamGb: 8,
      recommendedRamGb: 12,
    },
    discoveryConfidence: "high",
    notes: ["Fast starter model for smaller laptops."],
  },
  {
    id: "Qwen/Qwen2.5-7B-Instruct",
    kind: "text",
    family: "qwen",
    runtime: ["ollama", "transformers", "llamacpp"],
    tasks: ["text_generation", "writing", "general_chat", "documents"],
    localFriendly: true,
    estimatedRamGb: 12,
    speedTier: 4,
    qualityTier: 4,
    source: "seed",
    gated: false,
    formats: ["gguf", "safetensors"],
    parameterClass: "medium",
    contextWindow: 32768,
    multilingualSupport: "high",
    memoryProfile: {
      minRamGb: 12,
      recommendedRamGb: 16,
      minVramGb: 8,
    },
    discoveryConfidence: "high",
    notes: ["Strong general-purpose local text model."],
  },
  {
    id: "Qwen/Qwen2.5-Coder-7B-Instruct",
    kind: "text",
    family: "qwen",
    runtime: ["ollama", "transformers", "llamacpp"],
    tasks: ["text_generation", "coding", "general_chat"],
    localFriendly: true,
    estimatedRamGb: 14,
    speedTier: 3,
    qualityTier: 5,
    source: "seed",
    gated: false,
    formats: ["gguf", "safetensors"],
    parameterClass: "medium",
    contextWindow: 32768,
    toolUseSupport: "strong",
    memoryProfile: {
      minRamGb: 14,
      recommendedRamGb: 18,
      minVramGb: 8,
    },
    discoveryConfidence: "high",
    notes: ["Bias this upward for coding-heavy workloads."],
  },
  {
    id: "Qwen/Qwen2.5-14B-Instruct",
    kind: "text",
    family: "qwen",
    runtime: ["ollama", "transformers", "llamacpp"],
    tasks: ["text_generation", "writing", "general_chat", "documents"],
    localFriendly: true,
    estimatedRamGb: 20,
    speedTier: 2,
    qualityTier: 5,
    source: "seed",
    gated: false,
    formats: ["gguf", "safetensors"],
    parameterClass: "large",
    contextWindow: 32768,
    multilingualSupport: "high",
    memoryProfile: {
      minRamGb: 20,
      recommendedRamGb: 28,
      minVramGb: 10,
    },
    discoveryConfidence: "high",
    notes: ["Quality-first option when you have plenty of unified memory or VRAM."],
  },
];
