import type { CandidateModel } from "../shared/types.js";

export const curatedVisionModels: CandidateModel[] = [
  {
    id: "microsoft/Florence-2-base",
    kind: "vision",
    family: "florence",
    runtime: ["transformers"],
    tasks: ["vision", "documents", "screenshots"],
    localFriendly: true,
    estimatedRamGb: 6,
    estimatedVramGb: 6,
    speedTier: 4,
    qualityTier: 3,
    source: "seed",
    gated: false,
    formats: ["safetensors"],
    parameterClass: "small",
    memoryProfile: {
      minRamGb: 6,
      recommendedRamGb: 12,
      minVramGb: 6,
    },
    discoveryConfidence: "medium",
    notes: ["Lightweight vision helper; better for captions and simple image tasks than long doc QA."],
  },
  {
    id: "Qwen/Qwen2.5-VL-3B-Instruct",
    kind: "vision",
    family: "qwen",
    runtime: ["transformers", "ollama"],
    tasks: ["vision", "documents", "screenshots", "photos"],
    localFriendly: true,
    estimatedRamGb: 10,
    estimatedVramGb: 8,
    speedTier: 4,
    qualityTier: 4,
    source: "seed",
    gated: false,
    formats: ["safetensors"],
    parameterClass: "small",
    memoryProfile: {
      minRamGb: 10,
      recommendedRamGb: 16,
      minVramGb: 8,
    },
    discoveryConfidence: "medium",
    notes: ["Good fit for screenshots and scanned documents."],
  },
  {
    id: "llava-hf/llava-1.5-7b-hf",
    kind: "vision",
    family: "llava",
    runtime: ["transformers"],
    tasks: ["vision", "screenshots", "photos"],
    localFriendly: false,
    estimatedRamGb: 16,
    estimatedVramGb: 10,
    speedTier: 2,
    qualityTier: 4,
    source: "seed",
    gated: false,
    formats: ["safetensors"],
    parameterClass: "medium",
    memoryProfile: {
      minRamGb: 16,
      recommendedRamGb: 24,
      minVramGb: 10,
    },
    discoveryConfidence: "medium",
  },
];
