import type { CandidateModel } from "../shared/types.js";

export const curatedEmbeddingModels: CandidateModel[] = [
  {
    id: "BAAI/bge-small-en-v1.5",
    kind: "embedding",
    family: "bge",
    runtime: ["transformers", "other"],
    tasks: ["embeddings", "documents"],
    localFriendly: true,
    estimatedRamGb: 2,
    embeddingDimensions: 384,
    speedTier: 5,
    qualityTier: 3,
    source: "seed",
    gated: false,
    formats: ["safetensors"],
    parameterClass: "small",
    memoryProfile: {
      minRamGb: 2,
      recommendedRamGb: 4,
    },
    discoveryConfidence: "high",
    notes: ["Good default for smaller machines and quick indexing."],
  },
  {
    id: "BAAI/bge-base-en-v1.5",
    kind: "embedding",
    family: "bge",
    runtime: ["transformers", "other"],
    tasks: ["embeddings", "documents"],
    localFriendly: true,
    estimatedRamGb: 4,
    embeddingDimensions: 768,
    speedTier: 4,
    qualityTier: 4,
    source: "seed",
    gated: false,
    formats: ["safetensors"],
    parameterClass: "small",
    memoryProfile: {
      minRamGb: 4,
      recommendedRamGb: 6,
    },
    discoveryConfidence: "high",
    notes: ["Balanced embedding quality for document workloads."],
  },
  {
    id: "mixedbread-ai/mxbai-embed-large-v1",
    kind: "embedding",
    family: "mixedbread",
    runtime: ["transformers", "other"],
    tasks: ["embeddings", "documents"],
    localFriendly: true,
    estimatedRamGb: 6,
    embeddingDimensions: 1024,
    speedTier: 3,
    qualityTier: 5,
    source: "seed",
    gated: false,
    formats: ["safetensors"],
    parameterClass: "medium",
    memoryProfile: {
      minRamGb: 6,
      recommendedRamGb: 8,
    },
    discoveryConfidence: "medium",
  },
  {
    id: "intfloat/multilingual-e5-small",
    kind: "embedding",
    family: "e5",
    runtime: ["transformers", "other"],
    tasks: ["embeddings", "documents"],
    localFriendly: true,
    estimatedRamGb: 3,
    embeddingDimensions: 384,
    speedTier: 4,
    qualityTier: 4,
    source: "seed",
    gated: false,
    formats: ["safetensors"],
    parameterClass: "small",
    memoryProfile: {
      minRamGb: 3,
      recommendedRamGb: 5,
    },
    discoveryConfidence: "high",
    notes: ["Compact multilingual retrieval option."],
  },
];
