import type { CandidateModel } from "../shared/types.js";

export const curatedImageModels: CandidateModel[] = [
  {
    id: "stabilityai/sd-turbo",
    kind: "image",
    family: "stable-diffusion",
    runtime: ["transformers", "other"],
    tasks: ["text_to_image"],
    localFriendly: true,
    estimatedRamGb: 8,
    estimatedVramGb: 8,
    speedTier: 4,
    qualityTier: 3,
    source: "seed",
    gated: false,
    formats: ["safetensors"],
    parameterClass: "small",
    memoryProfile: {
      minRamGb: 8,
      recommendedRamGb: 16,
      minVramGb: 8,
      recommendedVramGb: 10,
    },
    discoveryConfidence: "high",
    notes: ["Fastest image-generation seed candidate."],
  },
  {
    id: "black-forest-labs/FLUX.1-schnell",
    kind: "image",
    family: "flux",
    runtime: ["transformers", "other"],
    tasks: ["text_to_image"],
    localFriendly: false,
    estimatedRamGb: 16,
    estimatedVramGb: 12,
    speedTier: 2,
    qualityTier: 5,
    source: "seed",
    gated: false,
    formats: ["safetensors"],
    parameterClass: "large",
    memoryProfile: {
      minRamGb: 16,
      recommendedRamGb: 24,
      minVramGb: 12,
      recommendedVramGb: 16,
    },
    discoveryConfidence: "medium",
  },
  {
    id: "stabilityai/stable-diffusion-xl-base-1.0",
    kind: "image",
    family: "stable-diffusion",
    runtime: ["transformers", "other"],
    tasks: ["text_to_image"],
    localFriendly: false,
    estimatedRamGb: 22,
    estimatedVramGb: 14,
    speedTier: 2,
    qualityTier: 5,
    source: "seed",
    gated: false,
    formats: ["safetensors"],
    parameterClass: "large",
    memoryProfile: {
      minRamGb: 22,
      recommendedRamGb: 32,
      minVramGb: 14,
      recommendedVramGb: 18,
    },
    discoveryConfidence: "high",
    notes: ["Heavier SDXL-class option; needs a strong GPU or large unified memory."],
  },
];
