import type { CandidateVariant } from "../shared/types.js";

const v = (x: CandidateVariant) => x;

/** Curated deployable variants for seed models (IDs match curated registries). */
export const VARIANTS_BY_MODEL_ID: Record<string, CandidateVariant[]> = {
  "google/gemma-2-2b-it": [
    v({
      variantId: "gemma-2-2b-it|ollama|q4",
      baseModelId: "google/gemma-2-2b-it",
      format: "gguf",
      precision: "q4",
      quantLabel: "Q4_K_M",
      engineCompatibility: ["ollama", "lm_studio", "llamacpp"],
      estimatedRamGb: 5.5,
      contextClass: "standard",
      speedModifier: 1.05,
      qualityModifier: 0.95,
      localFriendly: true,
      deployHint: "ollama pull gemma2:2b",
    }),
    v({
      variantId: "gemma-2-2b-it|transformers|fp16",
      baseModelId: "google/gemma-2-2b-it",
      format: "safetensors",
      precision: "fp16",
      engineCompatibility: ["transformers", "vllm", "mlx"],
      estimatedRamGb: 7,
      contextClass: "standard",
      speedModifier: 0.92,
      qualityModifier: 1.08,
      localFriendly: true,
      deployHint: "Load via Transformers/MLX; expect higher RAM than GGUF Q4.",
    }),
  ],
  "meta-llama/Llama-3.2-3B-Instruct": [
    v({
      variantId: "llama-3.2-3b|ollama|q4",
      baseModelId: "meta-llama/Llama-3.2-3B-Instruct",
      format: "gguf",
      precision: "q4",
      quantLabel: "Q4_K_M",
      engineCompatibility: ["ollama", "lm_studio", "llamacpp"],
      estimatedRamGb: 6,
      contextClass: "standard",
      speedModifier: 1.05,
      qualityModifier: 0.95,
      localFriendly: true,
      deployHint: "ollama pull llama3.2:3b",
    }),
    v({
      variantId: "llama-3.2-3b|transformers|bf16",
      baseModelId: "meta-llama/Llama-3.2-3B-Instruct",
      format: "safetensors",
      precision: "bf16",
      engineCompatibility: ["transformers", "vllm", "mlx"],
      estimatedRamGb: 8,
      contextClass: "standard",
      speedModifier: 0.9,
      qualityModifier: 1.1,
      localFriendly: true,
    }),
  ],
  "microsoft/Phi-3.5-mini-instruct": [
    v({
      variantId: "phi-3.5-mini|transformers|int8",
      baseModelId: "microsoft/Phi-3.5-mini-instruct",
      format: "safetensors",
      precision: "int8",
      engineCompatibility: ["transformers", "mlx", "vllm"],
      estimatedRamGb: 7,
      contextClass: "standard",
      speedModifier: 1,
      qualityModifier: 1,
      localFriendly: true,
      deployHint: "Phi-3.5 is simplest via Transformers; Ollama builds vary by tag.",
    }),
    v({
      variantId: "phi-3.5-mini|ollama|q4",
      baseModelId: "microsoft/Phi-3.5-mini-instruct",
      format: "gguf",
      precision: "q4",
      quantLabel: "Q4_K_M",
      engineCompatibility: ["ollama", "lm_studio", "llamacpp"],
      estimatedRamGb: 6.5,
      contextClass: "standard",
      speedModifier: 1.02,
      qualityModifier: 0.98,
      localFriendly: true,
      deployHint: "Check `ollama pull` for an available phi3.5 tag on your machine.",
    }),
  ],
  "Qwen/Qwen2.5-7B-Instruct": [
    v({
      variantId: "qwen2.5-7b|ollama|q4",
      baseModelId: "Qwen/Qwen2.5-7B-Instruct",
      format: "gguf",
      precision: "q4",
      quantLabel: "Q4_K_M",
      engineCompatibility: ["ollama", "lm_studio", "llamacpp"],
      estimatedRamGb: 11,
      contextClass: "standard",
      speedModifier: 1,
      qualityModifier: 1,
      localFriendly: true,
      deployHint: "ollama pull qwen2.5:7b-instruct-q4_K_M",
    }),
    v({
      variantId: "qwen2.5-7b|transformers|q8",
      baseModelId: "Qwen/Qwen2.5-7B-Instruct",
      format: "safetensors",
      precision: "q8",
      engineCompatibility: ["transformers", "vllm", "mlx"],
      estimatedRamGb: 14,
      contextClass: "long",
      speedModifier: 0.85,
      qualityModifier: 1.12,
      localFriendly: true,
    }),
  ],
  "Qwen/Qwen2.5-Coder-7B-Instruct": [
    v({
      variantId: "qwen2.5-coder-7b|ollama|q4",
      baseModelId: "Qwen/Qwen2.5-Coder-7B-Instruct",
      format: "gguf",
      precision: "q4",
      quantLabel: "Q4_K_M",
      engineCompatibility: ["ollama", "lm_studio", "llamacpp"],
      estimatedRamGb: 12,
      contextClass: "standard",
      speedModifier: 1,
      qualityModifier: 1.02,
      localFriendly: true,
      deployHint: "ollama pull qwen2.5-coder:7b (or nearest available coder tag)",
    }),
    v({
      variantId: "qwen2.5-coder-7b|transformers|fp16",
      baseModelId: "Qwen/Qwen2.5-Coder-7B-Instruct",
      format: "safetensors",
      precision: "fp16",
      engineCompatibility: ["transformers", "vllm"],
      estimatedRamGb: 16,
      contextClass: "long",
      speedModifier: 0.82,
      qualityModifier: 1.1,
      localFriendly: true,
    }),
  ],
  "Qwen/Qwen2.5-14B-Instruct": [
    v({
      variantId: "qwen2.5-14b|ollama|q4",
      baseModelId: "Qwen/Qwen2.5-14B-Instruct",
      format: "gguf",
      precision: "q4",
      quantLabel: "Q4_K_M",
      engineCompatibility: ["ollama", "lm_studio", "llamacpp"],
      estimatedRamGb: 18,
      contextClass: "long",
      speedModifier: 0.95,
      qualityModifier: 1.08,
      localFriendly: true,
      deployHint: "ollama pull qwen2.5:14b-instruct-q4_K_M",
    }),
    v({
      variantId: "qwen2.5-14b|transformers|q5",
      baseModelId: "Qwen/Qwen2.5-14B-Instruct",
      format: "safetensors",
      precision: "q5",
      engineCompatibility: ["transformers", "vllm"],
      estimatedRamGb: 22,
      contextClass: "long",
      speedModifier: 0.78,
      qualityModifier: 1.15,
      localFriendly: true,
    }),
  ],
  "Qwen/Qwen2.5-VL-3B-Instruct": [
    v({
      variantId: "qwen2.5-vl-3b|transformers|fp16",
      baseModelId: "Qwen/Qwen2.5-VL-3B-Instruct",
      format: "safetensors",
      precision: "fp16",
      engineCompatibility: ["transformers", "mlx"],
      estimatedRamGb: 9,
      estimatedVramGb: 7,
      contextClass: "standard",
      speedModifier: 0.95,
      qualityModifier: 1.05,
      localFriendly: true,
      deployHint: "Use Transformers or MLX; reserve extra RAM for image tokens.",
    }),
    v({
      variantId: "qwen2.5-vl-3b|ollama|q4",
      baseModelId: "Qwen/Qwen2.5-VL-3B-Instruct",
      format: "gguf",
      precision: "q4",
      quantLabel: "Q4_K_M",
      engineCompatibility: ["ollama", "lm_studio"],
      estimatedRamGb: 7.5,
      estimatedVramGb: 6,
      contextClass: "standard",
      speedModifier: 1.02,
      qualityModifier: 0.98,
      localFriendly: true,
      deployHint: "Use a vision-capable Ollama tag when available.",
    }),
  ],
};

export function getVariantsForModel(modelId: string): CandidateVariant[] {
  return VARIANTS_BY_MODEL_ID[modelId] ?? [];
}
